# Generated by Django 4.0.4 on 2022-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='poke',
            name='attack',
        ),
        migrations.AddField(
            model_name='poke',
            name='attack',
            field=models.ManyToManyField(to='main_app.attack'),
        ),
    ]
